name: '🐞 Bug Report'
description: 'Create a detailed report to help us improve'
title: 'BUG:'
labels: ['Bug']
body:
  - type: checkboxes
    attributes:
      label: 'Preliminary Check'
      description: 'Please confirm the following before reporting a bug.'
      options:
        - label: 'I have searched the existing issues'
          required: true
        - label: 'This issue is reproducible'
          required: true
  - type: textarea
    attributes:
      label: 'Bug Summary'
      description: 'Provide a concise summary of the bug, including what you expected to happen and what actually happened.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Steps to Reproduce'
      description: 'List the steps to reproduce the bug. Include specific details so that we can easily replicate the issue.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected Behavior'
      description: 'What did you expect to happen instead?'
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'Screenshots/Logs'
      description: 'If applicable, add screenshots or logs that can help us understand the issue better.'
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 'Additional Information'
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I'm a GSSOC'24 contributor"
        - label: 'I want to work on this issue'
        - label: 'I can provide more details if needed'
