name: Update Repository structure

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
      - master

jobs:
  detect-and-update-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # ✅ Use your secret token
        run: python .github/scripts/update_structure.py

      - name: Commit and push if changed
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" 
          git config user.name "github-actions[bot]"
          git add . 
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update repo structure" && \
            git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/Jaishree2310/GlassyUI-Components.git HEAD:main
          )
